name: 'Bundle size diff reporter'
description: 'Post bundle size difference compared to another branch'
inputs:
  branch:
    description: 'Branch to compare to'
    required: true
    default: 'main'
  paths:
    description: 'Paths to json file bundle size report or folder containing bundles'
    required: true
    default: '/'
  onlyDiff:
    description: 'Report only different sizes'
    required: false
    default: 'false'

  # Comment inputs
  comment:
    description: 'Post comment'
    required: false
    default: 'true'
  header:
    description: 'Comment header'
    required: false
    default: 'Bundle size report'
  append:
    description: 'Append comment'
    required: false
  ghToken:
    description: 'Github token'
    required: false

branding:
  icon: box
  color: green

runs:
  using: "composite"
  steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        path: br-base
        token: ${{ inputs.ghToken }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Calculate bundle size
      id: bundleSize
      run: node ./dist/index.js
      env:
        PATHS: ${{ inputs.paths }}
        ONLY_DIFF: ${{ inputs.onlyDiff }}
      shell: bash

    - name: Bundle size summary
      if: ${{ steps.bundleSize.outputs.summary }} != ''
      run: |
        echo "${{ steps.bundleSize.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
      shell: bash
    
    - uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ steps.bundleSize.outputs.summary }} != '' && ${{ inputs.comment }} == 'true'
      with:
        GITHUB_TOKEN: ${{ inputs.ghToken }}
        number: ${{ github.event.pull_request.number }}
        header: ${{ inputs.header }}
        message: ${{ steps.bundleSize.outputs.summary }}
